#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Catppuccin-Mocha-Standard-Mauve$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Catppuccin-Mocha-Standard-Mauve$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Standard-Mauve$SWITCHTO"
gsettings set org.gnome.desktop.interface icon-theme "Catppuccin-Mocha-Standard-Mauve$SWITCHTO"

#restart the waybar
killall -SIGUSR2 waybar