#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-D-0 -d  VI VII VIII IX X


bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#99CC99"
bspc config normal_border_color "#000000"
bspc config presel_border_color "#8F3724"
bspc config urgent_border_color "#504339"
bspc config focused_private_border_color "#35BF5C"
bspc config border_width 3 


bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "vlc" desktop=^4 follow=true
bspc rule -a "Pavucontrol" state=floating follow=true 

bspc config -m HDMI-0 top_padding 55

bspc config -m DVI-D-0 top_padding 55
bspc config -m DVI-D-0 bottom_padding 21

wmname LG3D

# Autostart
picom --config $HOME/.config/bspwm/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
onedriver &
nitrogen --restore  
numlockx on &
plank &
$HOME/.config/polybar/launch.sh --colorblocks &