#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-D-0 -d  VI VII VIII IX X

bspc config border_width 3
bspc config focused_border_color \#03fca1
bspc config normal_border_color \#cba6f7
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "vlc" desktop=^4 follow=true

bspc config top_padding 50
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

wmname LG3D

# Autostart
picom --config $HOME/.config/bspwm/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
onedriver &
plank &
nitrogen --restore  
numlockx on &
$HOME/.config/polybar/launch.sh --colorblocks &
