#! /bin/sh

# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Run EWW.
# $HOME/.local/bin/eww -c $HOME/.config/eww/bar --restart open bar &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &

# Run Picom.
#picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 --config $HOME/.config/picom/picom.conf &
# picom -b --config $HOME/.config/picom/picom.conf &
compfy -b

# Run polkit daemon if doesn't started.
[ -n "$(pidof polkit-gnome-authentication-agent-1)" ] || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Run power manager.
xfce4-power-manager &

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Restore Wallpaper
#sh $HOME/.config/bspwm/scripts/wallpaper.sh
nitrogen --restore

# Enable numlock
numlockx on &

# Fix cursor.
xsetroot -cursor_name left_ptr

# Nm-Applet for Proton Vpn
nm-applet &   
blueman-applet &

# Polybar
$HOME/.config/polybar/launch.sh &

# Better LockScren
pkill xautolock
xautolock -time 5 -locker "betterlockscreen -l" -notify 30 -notifier "notify-send 'Locker' 'Locking screen in 30 seconds'" &

pkill plank
plank &

pkill hidamari-player
# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

bspc wm -O HDMI-0 DVI-D-0

bspc monitor DVI-D-0 -d  6 7 8 9 10

bspc monitor HDMI-0 -d 1 2 3 4 5


rule kitty                   state=floating center=true rectangle=800x425+0+0
rule Code                    desktop=1   follow=on focus=on
rule Brave-browser                 desktop=2   follow=on focus=on
rule Nemo                    desktop=3   follow=on focus=on
rule Spotify                 desktop=6   follow=on focus=on
rule discord                 desktop=7   follow=on focus=on
rule Blueman-manager         state=floating center=true rectangle=1376x625+0+0
rule Pavucontrol             state=floating center=true rectangle=1376x625+0+0
rule Nitrogen                state=floating center=true rectangle=1376x625+0+0
rule gnome-calculator        state=floating center=true 
rule gnome-calendar          state=floating center=true 
rule leagueclientux.exe      state=floating center=true 
rule Plank                   layer=above manage=on border=off

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

config border_width 3
config window_gap 10
config split_ratio 0.50
config -m HDMI-0 top_padding 30
config -m HDMI-0 bottom_padding 30

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

config focused_border_color "#99CC99"
config normal_border_color "#000000"
config presel_border_color "#8F3724"
config urgent_border_color "#504339"
config focused_private_border_color "#35BF5C"

